@startuml Sistema de Gestión Empresarial

abstract class Empleado {
    - nombre_completo
    - fecha_nacimiento
    - sueldo_bruto
    - retencion
    - calcular_edad()
}

class Cliente {
    - nombre_completo
    - fecha_nacimiento
    - numero_telefono
}

class Supervisor {
    - puesto
    - modificar_retencion()
    - modificar_sueldo_bruto()
}

class Sistema_de_Pagos {
    + obtener_retencion()
    + calcular_salario()
}

class Empresa {
    - nombre_corporativo
    - CIF 
    - direccion_fiscal
}

Empleado <|-- Supervisor
Supervisor "1" --- "0..n" Empleado : supervisa
Sistema_de_Pagos .> Empleado : calcula_salario_a
Empresa "1..*" -- "0..*" Cliente : representado_por
@enduml